# build environment
FROM node:lts-alpine as build
ARG HOST
ENV HOST=${HOST}
WORKDIR /app
COPY . .
RUN yarn
RUN yarn build

FROM staticfloat/nginx-certbot
ENV CERTBOT_EMAIL=alan.cov@icloud.com
COPY --from=build /app/build /usr/share/nginx/html