# build environment
FROM --platform=linux/amd64 node:lts-alpine as build
WORKDIR /app
COPY . .
RUN yarn
RUN yarn build

FROM --platform=linux/amd64 staticfloat/nginx-certbot
ENV CERTBOT_EMAIL=alan.cov@icloud.com
COPY --from=build /app/build /usr/share/nginx/html