# build stage
FROM --platform=linux/amd64 node:lts-alpine
ARG HOST
ENV HOST=${HOST}
WORKDIR /home/node/code
COPY --chown=node:node package.json yarn.lock ./
RUN yarn install
COPY . /home/node/code
CMD ["yarn", "dev"]