# build environment
FROM --platform=linux/amd64 node:lts-alpine as build
ARG HOST
ENV HOST=${HOST}
WORKDIR /app
COPY . .
RUN yarn
RUN yarn build

FROM --platform=linux/amd64 nginx:latest
COPY --from=build /app/build /usr/share/nginx/html