version: "3"
services:
  client:
    image: client:dev
    build:
      dockerfile: Dockerfile.dev
      args:
        HOST: localhost
    ports:
      - 1234:1234
      - 1235:1235
    volumes:
      - ./client:/home/node/code
      - /home/node/code/node_modules
  server:
    image: server:dev
    build:
      dockerfile: Dockerfile.dev
    ports:
      - 4000:4000
    volumes:
      - ./server:/home/node/code
      - /home/node/code/node_modules
  nba:
    image: nba:dev
    build:
      dockerfile: Dockerfile.dev
    volumes:
      - ./nba:/project
    ports:
      - 3001:3001
  mlb:
    image: mlb:dev
    build:
      dockerfile: Dockerfile.dev
    volumes:
      - ./mlb:/project
    ports:
      - 3002:3002
  crawler:
    image: crawler:dev
    build:
      dockerfile: Dockerfile.dev
    volumes:
      - ./crawler:/project
    ports:
      - 5000:5000
  db:
    ports:
      - 5432:5432
  mongo:
    ports:
      - 27017:27017
  analyzer:
    image: analyzer:dev
    build:
      context: analyzer
      dockerfile: Dockerfile.dev
    volumes:
      - ./analyzer:/project
    ports:
      - 5001:5000
    depends_on:
      - server
  nginx:
    image: nginx:dev
    build:
      context: nginx
      dockerfile: Dockerfile.dev
    ports:
      - 80:80
    depends_on:
      - client
      - server

volumes:
  postgres:
