version: "3"
services:
  client:
    image: client:prod
    build:
      context: client
      dockerfile: Dockerfile.prod
      args:
        HOST: ${HOST}
    volumes:
      - ./client/nginx:/etc/nginx/conf.d
    ports:
      - 80:80
    environment:
      NODE_ENV: production
  server:
    image: server:prod
    build:
      context: server
      dockerfile: Dockerfile.prod
  nba:
    image: nba:prod
    build:
      context: nba
      dockerfile: Dockerfile.prod
      args:
        SECRET_KEY: ${SECRET_KEY}
  mlb:
    image: mlb:prod
    build:
      context: mlb
      dockerfile: Dockerfile.prod
      args:
        SECRET_KEY: ${SECRET_KEY}
  auth:
    image: auth:prod
    build:
      context: auth
      dockerfile: Dockerfile.prod
      args:
        SECRET_KEY: ${SECRET_KEY}
  crawler:
    image: crawler:prod
    build:
      context: crawler
      dockerfile: Dockerfile.prod
  analyzer:
    image: analyzer:prod
    build:
      context: analyzer
      dockerfile: Dockerfile.prod

volumes:
  postgres:
