version: "3"
services:
  client:
    build: client
    depends_on:
      - server
  server:
    build: server
    depends_on:
      - nba
      - mlb
      - auth
  auth:
    build: auth
    depends_on:
      - db
      - crawler
  nba:
    build: nba
    depends_on:
      - db
      - crawler
      - analyzer
  mlb:
    build: mlb
    depends_on:
      - db
      - crawler
  crawler:
    build: crawler
    depends_on:
      - mongo
  db:
    image: postgres
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - 5432:5432
  mongo:
    image: mongo
    volumes:
      - mongo:/data/db
    ports:
      - 27017:27017

volumes:
  postgres:
volumes:
  mongo:
