version: "3"
services:
  nginx:
    build: nginx
    ports:
      - 80:80
    depends_on:
      - client
      - server
  client:
    image: client:prod
    build:
      dockerfile: Dockerfile.prod
      args:
        HOST: ${HOST}
  server:
    image: server:prod
    build:
      dockerfile: Dockerfile.prod
      args:
        HOST: ${HOST}
  nba:
    image: nba:prod
    build:
      dockerfile: Dockerfile.prod
      args:
        SECRET_KEY: ${SECRET_KEY}
  mlb:
    image: mlb:prod
    build:
      dockerfile: Dockerfile.prod
      args:
        SECRET_KEY: ${SECRET_KEY}

volumes:
  postgres:
