version: "3.4"
services:
  client:
    image: client:prod
    build:
      context: client
      dockerfile: Dockerfile.prod
      args:
        HOST: ${HOST}
    ports:
      - 80:80/tcp
      - 443:443/tcp
    volumes:
      - ./client/nginx:/etc/nginx/user.conf.d:ro
      - /etc/letsencrypt/:/etc/letsencrypt/
  server:
    image: server:prod
    build:
      context: server
      dockerfile: Dockerfile.prod
  auth:
    image: auth:prod
    build:
      context: auth
      dockerfile: Dockerfile.prod
      args:
        SECRET_KEY: ${SECRET_KEY}
  football:
    image: football:prod
    build:
      context: football
      dockerfile: Dockerfile.prod
      args:
        SECRET_KEY: ${SECRET_KEY}
  sidekiq:
    image: sidekiq:prod
    build:
      context: football
      dockerfile: Dockerfile.prod
    command: bundle exec sidekiq
    depends_on:
      - db
      - redis
      - crawler
    volumes:
      - ./football:/project
      - /project/tmp
    environment:
      - REDIS_URL_SIDEKIQ=redis://redis:6379/1
  crawler:
    image: crawler:prod
    build:
      context: crawler
      dockerfile: Dockerfile.prod
  db:
    image: postgres:15
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - "5432:5432"
  redis:
    image: redis:7.2.1-alpine
    command: redis-server
    ports:
      - "6379:6379"
    volumes:
      - redis:/data

volumes:
  postgres:
  redis:
  letsencrypt:
