version: "3"
services:
  client:
    image: client:test
    build:
      dockerfile: Dockerfile.test
    volumes:
      - ./client:/home/node/code
      - /home/node/code/node_modules
  server:
    image: server:test
    build:
      dockerfile: Dockerfile.test
  nba:
    image: nba:test
    build:
      dockerfile: Dockerfile.test
  mlb:
    image: mlb:test
    build:
      dockerfile: Dockerfile.test
  crawler:
    image: crawler:test
    build:
      dockerfile: Dockerfile.test

volumes:
  postgres:
