version: "3.4"
services:
  client:
    image: client:prod
    build:
      context: client
      dockerfile: Dockerfile.prod
      args:
        HOST: ${HOST}
    ports:
      - 80:80/tcp
      - 443:443/tcp
    volumes:
      - ./client/nginx:/etc/nginx/user.conf.d:ro
      - /etc/letsencrypt/:/etc/letsencrypt/
  server:
    image: server:prod
    build:
      context: server
      dockerfile: Dockerfile.prod
  football:
    image: football:prod
    build:
      context: football
      dockerfile: Dockerfile.prod
      args:
        SECRET_KEY: ${SECRET_KEY}
  auth:
    image: auth:prod
    build:
      context: auth
      dockerfile: Dockerfile.prod
      args:
        SECRET_KEY: ${SECRET_KEY}
  crawler:
    image: crawler:prod
    build:
      context: crawler
      dockerfile: Dockerfile.prod
  db:
    image: postgres
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - "5432:5432"

volumes:
  postgres:
  letsencrypt:
