version: "3"
services:
  nginx:
    build:
      dockerfile: Dockerfile.dev
  client:
    build:
      dockerfile: Dockerfile.dev
      args:
        HOST: localhost
    ports:
      - 1234:1234
      - 1235:1235
    volumes:
      - ./client:/home/node/code
      - /home/node/code/node_modules
  server:
    ports:
      - 4000:4000
    volumes:
      - ./server:/home/node/code
      - /home/node/code/node_modules
  nba:
    build:
      dockerfile: Dockerfile.dev
    volumes:
      - ./nba:/project
    ports:
      - 3001:3001
  mlb:
    build:
      dockerfile: Dockerfile.dev
    volumes:
      - ./mlb:/project
    ports:
      - 3002:3002
  crawler:
    volumes:
      - ./crawler:/project
    ports:
      - 5000:5000
  db:
    ports:
      - 5432:5432
  mongo:
    ports:
      - 27017:27017

volumes:
  postgres:
