version: "3"
services:
  nginx:
    build:
      dockerfile: Dockerfile.prod
  client:
    build:
      dockerfile: Dockerfile.prod
      args:
        HOST: ${HOST}
  server:
    build:
      dockerfile: Dockerfile.prod
      args:
        HOST: ${HOST}
  nba:
    build:
      dockerfile: Dockerfile.prod
      args:
        SECRET_KEY: ${SECRET_KEY}
  mlb:
    build:
      dockerfile: Dockerfile.prod
      args:
        SECRET_KEY: ${SECRET_KEY}

volumes:
  postgres:
