FROM --platform=linux/amd64 python:3.8

# Adding trusting keys to apt for repositories

RUN wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -

# Adding Google Chrome to the repositories

RUN sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'

# Updating apt to see and install Google Chrome

RUN apt-get -y update
RUN apt-get install -y google-chrome-stable

# Set display port as an environment variable
ENV DISPLAY=:99
ENV FLASK_ENV=development
ENV PYTHONUNBUFFERED=1

RUN pip install pipenv
ENV PROJECT_DIR /project
WORKDIR ${PROJECT_DIR}
COPY Pipfile ${PROJECT_DIR}/
RUN pipenv install
COPY . .

CMD ["pipenv", "run", "python", "src/app.py"]