---
- name: Stop Docker Compose containers
  community.general.docker_compose:
    project_src: /home/{{user_name}}
    state: absent
  tags:
    - shutdown

- name: List all Docker images
  command: docker image ls -q
  register: image_ids
  tags:
    - shutdown

- name: Remove Docker images
  command: docker rmi "{{ item }}"
  with_items: "{{ image_ids.stdout_lines }}"
  tags:
    - shutdown
