FROM python:3.8
ENV FLASK_ENV=production
ENV PYTHONUNBUFFERED=1
RUN pip install pipenv
ENV PROJECT_DIR /project
WORKDIR ${PROJECT_DIR}
COPY Pipfile ${PROJECT_DIR}/
RUN pipenv install --deploy
COPY . .

CMD ["python", "src/main.py"]