FROM python:3.8
RUN pip install pipenv
ENV PROJECT_DIR /project
WORKDIR ${PROJECT_DIR}
COPY Pipfile Pipfile.lock ${PROJECT_DIR}/
RUN pipenv install --system --deploy
COPY . .

CMD ["python", "main.py"]