FROM ruby:2.7.2-slim

ARG SECRET_KEY
ENV SECRET_KEY=${SECRET_KEY}
ENV RAILS_ENV=production
RUN apt-get update -qq && apt-get install -y build-essential libpq-dev
RUN mkdir /project
WORKDIR /project

COPY Gemfile Gemfile.lock ./
RUN gem install bundler --no-document
RUN bundle install --no-binstubs --jobs $(nproc) --retry 3
COPY . .

CMD ./docker-entrypoint.sh