FROM --platform=linux/amd64 ruby:2.7-slim-bullseye

RUN apt-get update -qq && apt-get install -y build-essential libpq-dev
RUN mkdir /project
WORKDIR /project

COPY Gemfile Gemfile.lock ./
RUN gem install bundler -v 2.4.2 --no-document
RUN bundle install --no-binstubs --jobs $(nproc) --retry 3
COPY . .

CMD ./docker-entrypoint.sh