FROM ruby:2-slim

ENV RAILS_ENV=test
RUN apt-get update -qq && apt-get install -y build-essential libpq-dev
RUN mkdir /project
WORKDIR /project

COPY Gemfile Gemfile.lock ./
RUN gem install bundler --no-document
RUN bundle install --no-binstubs --jobs $(nproc) --retry 3
COPY . .

CMD ["bundle", "exec", "guard", "--no-bundler-warning", "--no-interactions"]