BASEBALL_PRESS_URL = "https://www.baseballpress.com"
BASEBALL_REFERENCE_URL = "https://www.baseball-reference.com"
BASKETBALL_REFERENCE_URL = "https://www.basketball-reference.com"
ESPN_URL = "https://www.espn.com"
FANGRAPHS_URL = "https://www.fangraphs.com"
SPORTS_BOOK_REVIEW_URL = "http://www.sportsbookreview.com"
WUNDERGROUND_URL = "https://www.wunderground.com"