default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  port: 5432
  username: postgres
  password:
  pool: 5

development:
  <<: *default
  database: nba_development

test:
  <<: *default
  database: nba_test

production:
  <<: *default
  database: nba_production
