---
- name: Perform local tasks
  hosts: localhost
  tasks:
    - name: get ECR password
      shell: aws ecr get-login-password --region us-west-1
      register: ecr_password

- name: Deploy sports app
  hosts: all
  gather_facts: false
  roles:
    - setup_server
    - setup_docker
    - deploy_app
